blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Learn more about the CZI grant 
    url: 
    about: Read the full CZI grant psoposal
  - name: ğŸ·  Jupyter accessibility roadmap
    url: https://github.com/orgs/jupyterlab/projects/1
    about: Keep up to date with the accessibility work within the Jupyter ecosystem